config/routes.rb
Rails.application.routes.draw do
  get 'index/show'
  get 'index/apply'
  get 'index/reject'
  devise_for :admins
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'

  #管理者アクション====================~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'

    get 'applies/reason'
    post 'applies/reject_update' => 'applies#reject_update'
    get 'applies/reject'
    resources :item_images
    resources :post_images ,only: [:index, :show]
    resources :pending_images ,only: [:index, :show, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :applies, only: [:index, :show, :update] do
      get 'apply' => 'applies#apply'
    end
    get 'reject' => 'applies#reject'
  end
  #===================================================================

  #ログイン時可能のアクション======================================================
  namespace :public do
    resources :post_images, only: [:index, :edit, :update, :destroy] do
      resources :post_image_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :item_images, only: [:index, :show] do
      resources :post_images, only: [:new, :show, :create]
      get 'download' => 'item_images#download'
      post 'download' => 'item_images#download'
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :following, :follower
      end
      resource :relationships, only: [:create, :destroy]
    end
  end
  #=================================================================================

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :admin
end

app/controllers/admin/applies_controller.rb
class Admin::AppliesController < ApplicationController
  def index
    @pending_images = PostImage.where(status: false)
  end

  def show
    #showについては1件の情報のみ取得したい
    
    @pending_image = PostImage.where(status: false).find(params[:id])
    @user = @pending_image.user
    @post_images = PostImage.where(user_id: @user.id).where(status: true)
    @item_image = ItemImage.find(@pending_image.item_image.id)
  end

  def update
    @pending_image = PostImage.find(params[:id])
    @pending_image.status = true
    #※今回、ユーザからの情報を受け取るわけではないので、「update」ではなく「save」
    if @pending_image.save
      redirect_to admin_apply_apply_path(@pending_image.id)
    else
      render admin_apply_path
    end
  end

  def apply
    @post_image = PostImage.select(:post_image_id)
  end

  def reason
    @post_image = PostImage.find(params[:post_image_id])
  end

  def reject_update
    @pending_image = PostImage.find(params[:post_image_id])
    #※今回、ユーザからの情報を受け取るわけではないので、「update」ではなく「save」
    @pending_image.reason = params[:reason]
    if @pending_image.save
      redirect_to admin_applies_reject_path
    else
      render admin_apply_path
    end
  end

  def reject
  end

  private#ストロングパラメータ======================

  def pending_image_params
    params.require(:post_image).permit(:reason)
  end


end

app/helpers/admin/applies_helper.rb
module Admin::AppliesHelper
end

app/views/admin/applies/apply.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12" style="text-align:center">
      <h2>承認完了</h2>
      <p>投稿画像の承認がされました！</p>
      <%#= attachment_image_tag @post_image, :image, width: "80%" %>
      <%= link_to "承認待機一覧に戻る", admin_applies_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/admin/applies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h4>承認待機一覧</h4>
      <% @pending_images.each do |pending_image| %>
        <div class="pending_list" style="display:inline-block;">
          <%= link_to admin_apply_path(pending_image.id) do %>
            <%= attachment_image_tag pending_image, :image, width: '200px', height: '200px', style: "object-fit:cover"  %><br />
            <div class="pending_image_info" style="text-align:center">
              <%= pending_image.title %> <br />
              <%= attachment_image_tag pending_image.user, :profile_image, width: '40px', height: '40px', fallback: "no_image.jpg" %>
              <%= pending_image.user.nickname %>
            </div>
            <br />
          <% end %>  
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/applies/reason.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12" style="display:inline-block;text-align:left">
      <h2>却下する理由</h2>
      <%= form_with url: admin_applies_reject_update_path, local: true do |f| %>
        <%= f.radio_button :reason, "線画を使用していない。" %>
        <%= f.label :reason, "線画を使用していない。" %><br />
        <%= f.radio_button :reason, "反社会表現がある。" %>
        <%= f.label :reason, "反社会表現がある。" %><br />
        <%= f.radio_button :reason, "他の著作物を侵害している。" %>
        <%= f.label :reason, "他の著作物を侵害している。" %><br />
        <%= f.radio_button :reason, "誹謗中傷などといった他者を傷つけるような表現がある。" %>
        <%= f.label :reason, "誹謗中傷などといった他者を傷つけるような表現がある。" %><br />
        <%= f.hidden_field :post_image_id, value: @post_image.id %>
        <%= f.submit "却下理由を送る", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/applies/reject.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>承認却下</h2>
      <p>却下しました。</p>
      
      <%= link_to "承認待機一覧に戻る", admin_applies_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/admin/applies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <table class="user_info_table" style="text-align:center">
        <tbody>
          <%= link_to admin_user_path(@pending_image.user) do %>
          <tr>
            <%= attachment_image_tag(@pending_image.user, :profile_image, :size => "200x200", fallback: "no_image.jpg") %>
          </tr>
          <br />
          <tr>
            <%= @pending_image.user.nickname %>
          </tr>
          <% end %>
          <br />
          <tr>
            <%= @pending_image.user.introduction %>
          </tr>
        </tbody>
      </table>
      <div class="old_post_image" style="text-align:center">
        <p>-ユーザの過去作品-</p>
        <table>
          <tbody>
            <% @post_images.each do |post_image| %>
              <tr>
                <td>
                   <%= attachment_image_tag post_image, :image, width: '80%' %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= post_image.title %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-lg-9" style="background-color:white">
        <!--タイトルと説明文を表示-->
      <h3><%= @pending_image.title %></h3>
      <p><%= @pending_image.img_introduction %></p>
      <p>投稿日時：<%= @pending_image.created_at %></p>
      <div class="item_image" style="text-align:center">
        <ul class="nav nav-tabs nav-fill justify-content-center">
          <li class="nav-item">
            <a href="#post" class="nav-link active" data-toggle="tab">投稿イラスト</a>
          </li>
          <li class="nav-item">
            <a href="#item" class="nav-link" data-toggle="tab">線画素材</a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="post" class="tab-pane active">
            <div id="modal-content">
            <%= attachment_image_tag @pending_image, :image, width: '80%' %>
            </div>
          </div>
          <div id="item" class="tab-pane">
            <%= attachment_image_tag @item_image, :image, width: '80%', format: 'png' %>
          </div>
        </div>
      </div>
      <div class="apply_reject">
        <%= form_with model: @pending_image, url: admin_apply_path, local:true do |f| %>
          <h2>-承認前の確認事項-</h2>
          <ul>
            <li>
              <%= f.check_box :reason, id: 'check-reason1', onclick:"click_check()" %>
              <%= f.label :reason, "素材となる線画を使用している。" %>
            </li>
            <li>
              <%= f.check_box :reason, id: 'check-reason2', onclick:"click_check()" %>
              <%= f.label :reason, "反社会表現がない。" %>
            </li>
            <li>
              <%= f.check_box :reason, id: 'check-reason3', onclick:"click_check()" %>
              <%= f.label :reason, "他の著作物を侵害するものではない。" %>
            </li>
            <li>
              <%= f.check_box :reason, id: 'check-reason4', onclick:"click_check()" %>
              <%= f.label :reason, "誹謗中傷など他者を傷つけるような表現がない。" %>
            </li>
          </ul>
          <div class="judge" style="text-align:center">
            <%= f.submit "承認する", class: "btn btn-success", id:'submit-apply', disabled: true %>
            <%= link_to "却下する", admin_applies_reason_path(post_image_id: @pending_image.id), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
function click_check() {
  var check1 = document.getElementById('check-reason1');
  var check2 = document.getElementById('check-reason2');
  var check3 = document.getElementById('check-reason3');
  var check4 = document.getElementById('check-reason4');
  var submit = document.getElementById('submit-apply');
  if (check1.checked && check2.checked && check3.checked && check4.checked) {
    submit.disabled = false;
  } else {
    submit.disabled = true;
  }
}
</script>