config/routes.rb
Rails.application.routes.draw do
  get 'index/show'
  get 'index/apply'
  get 'index/reject'
  devise_for :admins
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'

  #管理者アクション====================~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'

    get 'applies/reason'
    post 'applies/reject_update' => 'applies#reject_update'
    get 'applies/reject'
    resources :item_images
    resources :post_images ,only: [:index, :show]
    resources :pending_images ,only: [:index, :show, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :applies, only: [:index, :show, :update] do
      get 'apply' => 'applies#apply'
    end
    get 'reject' => 'applies#reject'
  end
  #===================================================================

  #ログイン時可能のアクション======================================================
  namespace :public do
    resources :post_images, only: [:index, :edit, :update, :destroy] do
      resources :post_image_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :item_images, only: [:index, :show] do
      resources :post_images, only: [:new, :show, :create]
      get 'download' => 'item_images#download'
      post 'download' => 'item_images#download'
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :following, :follower
      end
      resource :relationships, only: [:create, :destroy]
    end
  end
  #=================================================================================

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    
    unless @word == nil
      if @range == "投稿画像"
        @post_image = PostImage.where(['title LIKE ? ',  "%#{@word}%"]).where(status: 'true')
      elsif @range == "線画素材"
        @item_image = ItemImage.where(['item_title LIKE ?', "%#{@word}%"])
      else #Userだったら
        @user = User.where(['nickname LIKE ? ',  "%#{@word}%"])
      end
    else
      redirect_to request.referer and return
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="search_form" style="text-align:center">
  <%= form_with url: searches_search_path, local:true, method: :get do |search| %>
    <%= search.text_field :word %><!--検索ワード入力-->
    <%= search.select :range, options_for_select([['投稿画像'], ['線画素材'],['ユーザ']]) %>
    <%= search.submit "検索", class: "btn btn-secondary" %>
  <% end %>
  
</div>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-hover table-inverse">
        <div class="search_top">
          <p>"<%= @word %>"の検索結果</p>
        </div>
        <% if @range == "投稿画像" %>
          <h6><%= @range %>一覧</h6><br />
          <% if @word.blank? %>
            <p>検索結果はありませんでした。</p>
          <% else%>
            <% @post_image.each do |post_image| %>
            <!--「投稿画像」を選択された場合-->
              <div class="search_item" style="display:inline-block">
                <%= link_to public_item_image_post_image_path(item_image_id: post_image.item_image_id,id: post_image.id) do %>
                  <%= attachment_image_tag post_image, :image, width: '200px', height: '200px', style: "object-fit:cover"  %>
                  <p><%= post_image.title %></p>
                  <%= post_image.user.nickname %>
                <% end %>
              </div>
            <% end %>  
          <% end %>
        <% elsif @range == "線画素材" %><!--線画素材が選択された場合-->
          <%= @range %>一覧<br />
          <% if @word.blank? %>
            <p>検索結果はありませんでした。</p>
          <% else%>
            <% @item_image.each do |item_image| %>
              <div class="search_item" style="display:inline-block">
                <%= link_to public_item_image_path(item_image.id) do %>
                  <%= attachment_image_tag item_image, :image, width: '200px', height: '200px', style: "object-fit:cover"  %><br />
                  <%= item_image.item_title %>
                <% end %>
              </div>
            <% end %>  
          <% end %>
        <% else %><!--ユーザ検索-->
          <%= @range %>一覧
          <%#= link_to "全ユーザー一覧",public_users_path, class: 'btn btn-success' %><!--(実装中)-->
          <% if @word.blank? %>
            <p>検索したユーザ名は見つかりませんでした。</p>
          <% else %>
            <table width="75%">
              <thead>
                <tr>
                  <th width="25%" style="text-align:center">image</th>
                  <th width="50%" style="text-align:center">profile</th>
                </tr>
              </thead>
              <tbody>
                <% @user.each do |user| %>
                  <tr>
                    <td>
                      <div class="profile_image" style="text-align:center">
                        <%= attachment_image_tag(user, :profile_image, :size => "100x100", fallback: "no_image.jpg") %>
                      </div>
                    </td>
                    <td>
                      <%= link_to public_user_path(user) do %>
                        <h4><%= user.nickname %><br /></h4>
                      <% end %>
                      フォロー：<%= link_to following_public_user_path(user) do %><%= user.followings.count %><% end %><br />
                      フォロワー：<%= link_to follower_public_user_path(user) do %><%= user.followers.count %><% end %><br />
                      <p><%= user.introduction %></p>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        <% end %>  
      </div>
  </div>
</div>