config/routes.rb
Rails.application.routes.draw do
  get 'index/show'
  get 'index/apply'
  get 'index/reject'
  devise_for :admins
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'

  #管理者アクション====================~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'

    get 'applies/reason'
    post 'applies/reject_update' => 'applies#reject_update'
    get 'applies/reject'
    resources :item_images
    resources :post_images ,only: [:index, :show]
    resources :pending_images ,only: [:index, :show, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :applies, only: [:index, :show, :update] do
      get 'apply' => 'applies#apply'
    end
    get 'reject' => 'applies#reject'
  end
  #===================================================================

  #ログイン時可能のアクション======================================================
  namespace :public do
    resources :post_images, only: [:index, :edit, :update, :destroy] do
      resources :post_image_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :item_images, only: [:index, :show] do
      resources :post_images, only: [:new, :show, :create]
      get 'download' => 'item_images#download'
      post 'download' => 'item_images#download'
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :following, :follower
      end
      resource :relationships, only: [:create, :destroy]
    end
  end
  #=================================================================================

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :profile_header
  #個人のプロフィールにおけるバリデーション=========================
  validates :name, presence: true
  validates :nickname, presence: true
  validates :introduction, {length: {maximum: 250}}
  #validates :sex, inclusion: {in: [0, 1]}
    #=================================================================

  #アソシエーション--------------------------
  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_image_comments, dependent: :destroy
  #------------------------------------------

  #フォロー/フォロワー機能==========================================
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed #follower(前)

  has_many :passive_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower #followed(前)

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  #================================================================

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 #(管理者側)ユーザー一覧====================
  def index
    @users = User.all
  end
  #=========================================

  #管理者側のユーザ詳細画面=================
  def show
    @user = User.find_by(params[:id])
    @post_images = PostImage.where(user_id: @user.id, status: true)
    @pending_images = PostImage.where(status: false, user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if User.update(user_params)
      redirect_to public_user_path(@user.id)
    else
      render 'edit'
    end
  end
  #==========================================

  private #ストロングパラメータ=======================

  def user_params
    params.require(:user).permit(:status)
    #管理者側が変更できるのは退会ステータスのみのため
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 style="text-align:center">会員一覧</h2>
      <% @users.each do |user| %>
        <div class="user_profile">
          <div class="user_image" style="display:inline-block">
            <%= link_to admin_user_path(user.id) do %>  
              <%= attachment_image_tag user, :profile_image, size: "150x150", fallback: "no_image.jpg" %>
            <% end %>
          </div>
          <div class="user_infomation" style="display:inline-block;">
            <table>
              <tbody>
                <tr>
                  <td></td>
                  <td><%= user.nickname %></td>
                </tr>
                <tr>
                  <td>フォロー:</td>
                  <td>
                    <%= link_to following_public_user_path(user) do %>
                      <%= user.followings.count %>
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>フォロワー:</td>
                  <td>
                    <%= link_to follower_public_user_path(user) do %>
                      <%= user.followers.count %>
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td>introduction:</td>
                  <td><%= user.introduction %></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="post_easy">
            <%# @post_images.each do |post_image| %>
              <%#= link_to admin_apply_path(post_image.id) do %>
                <%#= attachment_image_tag post_image, :image, width: '150px', height: '150px', style: "object-fit:cover" %>
              <%# end %>
            <%# end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!--プロフィールのヘッダーを入れる場所-->
<div class="user_header" style="background-color:purple;">
  <%= attachment_image_tag(@user, :profile_header, width: '100%',height: '250px', fallback: "no_image.jpg") %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="profile_image" style="text-align:center">
        <%= attachment_image_tag(@user, :profile_image, :size => "200x200", fallback: "no_image.jpg") %><br />
        <h5><%= @user.nickname %></h5>
      </div>
      <table class="following_list" style="text-align:center">
      <tr>
        <td>フォロー</td>
        <td>
          <%= link_to following_public_user_path(@user) do %>
            <%= @user.followings.count %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>フォロワー</td>
        <td>
          <%= link_to follower_public_user_path(@user) do %>
            <%= @user.followers.count %>
          <% end %>
        </td>
      </tr>
    </table>
    </div>
    <div class="col-lg-9">
      <table class="table">
        <thead>
          <tr class="table_head">user infomation</tr>
        </thead>
        <tbody>
          <tr>
            <td class="bg-light" width="25%">ユーザニックネーム</td>
            <td class="bg-light" width="75%"><%= @user.nickname %></td>
          </tr>
          <tr>
            <td class="gn-light" width="25%">全投稿枚数</td>
            <td class="gn-light" width="75%"><%= @user.post_images.count %></td>
          </tr>
          <tr>
            <td class="bg-light" width="25%">　(承認数)</td>
            <td class="bg-light" width="75%">(<%= @post_images.count %>)</td>
          </tr>
          <tr>
            <td class="gn-light" width="25%">　(未承認数)</td>
            <td class="gn-light" width="75%">(<%= @pending_images.count %>)</td>
          </tr>
          <tr height="100">
            <td class="bg-light" width="25%">自己紹介</td>
            <td class="bg-light" width="75%"><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="post_image_list">
        <h4 style="text-align:center">-投稿一覧-</h4>
        <% @post_images.each do |post_image| %>
          <div class="post_image_list" style="display:inline-block;text-align:center">
            <%= link_to public_item_image_post_image_path(post_image.id) do %>
              <%= attachment_image_tag post_image, :image,width: '175px', height: '175px', style: "object-fit:cover"  %><br />
              <%= post_image.title %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="pending_images_list">
        <h4 style="text-align:center">-投稿待機一覧-</h4>
        <% @pending_images.each do |pending_image| %>
        <div class="pending_list" style="display:inline-block;text-align:center">
          <%= link_to admin_apply_path(pending_image.id) do %>
            <%= attachment_image_tag pending_image, :image, width: '175px', height: '175px', style: "object-fit:cover"  %><br />
            <%= pending_image.title %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>