config/routes.rb
Rails.application.routes.draw do
  get 'index/show'
  get 'index/apply'
  get 'index/reject'
  devise_for :admins
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'

  #管理者アクション====================~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'

    get 'applies/reason'
    post 'applies/reject_update' => 'applies#reject_update'
    get 'applies/reject'
    resources :item_images
    resources :post_images ,only: [:index, :show]
    resources :pending_images ,only: [:index, :show, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :applies, only: [:index, :show, :update] do
      get 'apply' => 'applies#apply'
    end
    get 'reject' => 'applies#reject'
  end
  #===================================================================

  #ログイン時可能のアクション======================================================
  namespace :public do
    resources :post_images, only: [:index, :edit, :update, :destroy] do
      resources :post_image_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :item_images, only: [:index, :show] do
      resources :post_images, only: [:new, :show, :create]
      get 'download' => 'item_images#download'
      post 'download' => 'item_images#download'
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :following, :follower
      end
      resource :relationships, only: [:create, :destroy]
    end
  end
  #=================================================================================

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #アソシエーション===========================       
  has_many :applies, dependent: :destroy       
  #===========================================
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :admin
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #アソシエーション================
  belongs_to :user
  belongs_to :post_image
  #================================
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  #画像認識
  attachment :image

  #バリデーションの追加============================
  validates :item_title, presence: true
  validates :image, presence: true
  #validates :item_introduction, presence: true
  #validates :status, inclusion:{in: [true, false]}
  #================================================

  #アソシエーション==========================
  has_many :post_images, dependent: :destroy
  #==========================================



end

app/models/post_image.rb
class PostImage < ApplicationRecord
  attachment :image

  #バリデーション==================
  validates :title, presence: true

  #================================

  #アソシエーション----------------
  belongs_to :user
  belongs_to :item_image
  has_many :favorites, dependent: :destroy
  has_many :post_image_comments, dependent: :destroy
  #--------------------------------

  #いいね機能--------------------------------
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  #------------------------------------------

  #タグ検索機能の追加====================
  acts_as_taggable_on :tags, :skills
  #scope :by_join_date, order("created_at DESC")
  #======================================

end

  #PostImage.tagged_with(params[:tag])
  #PostImage.tagged_with("タグ1")[0].id
  #PostImage.tagged_with("タグ1, タグ2")[0].id
  #PostImage.tagged_with("タグ1").by_join_date
  #User.tagged_with("タグ1").by_join_date.paginate(page: params[:page], per_page: 20)
  # 完全一致(AND検索)
  #User.tagged_with(["タグ1", "タグ2"], match_all: true)
  # 条件一致(OR検索)
  #User.tagged_with(["タグ1", "タグ2"], any: true)
  # 除外(含まないモノを検索)
  #User.tagged_with(["タグ1", "タグ2"], exclude: true)

app/models/post_image_comment.rb
class PostImageComment < ApplicationRecord
  #バリデーション=====================
  validates :comment, presence: true
  #コメント0文字はエラー
  #==================================
  #アソシエーション==================
  belongs_to :user
  belongs_to :post_image
  #==================================
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  #アソシエーション===========================
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  #===========================================
  
  #バリデーション=============================
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  #===========================================
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post_image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  attachment :profile_header
  #個人のプロフィールにおけるバリデーション=========================
  validates :name, presence: true
  validates :nickname, presence: true
  validates :introduction, {length: {maximum: 250}}
  #validates :sex, inclusion: {in: [0, 1]}
    #=================================================================

  #アソシエーション--------------------------
  has_many :post_images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_image_comments, dependent: :destroy
  #------------------------------------------

  #フォロー/フォロワー機能==========================================
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed #follower(前)

  has_many :passive_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower #followed(前)

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  #================================================================

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user
      public_user_path(resource)
    else
      admin_item_images_path
    end
  end

  def after_sign_out_path_for(resource)
    if current_user
      new_admin_session_path
    else
      root_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :sex])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    
    unless @word == nil
      if @range == "投稿画像"
        @post_image = PostImage.where(['title LIKE ? ',  "%#{@word}%"]).where(status: 'true')
      elsif @range == "線画素材"
        @item_image = ItemImage.where(['item_title LIKE ?', "%#{@word}%"])
      else #Userだったら
        @user = User.where(['nickname LIKE ? ',  "%#{@word}%"])
      end
    else
      redirect_to request.referer and return
    end
  end
end

app/helpers/admin/applies_helper.rb
module Admin::AppliesHelper
end

app/helpers/admin/item_images_helper.rb
module Admin::ItemImagesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer_item" style="text-align:center">
    <p>Y.O_@portfolio</p>
    <br />
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  
  <nav class="navbar navbar-expand-lg navbar-light">  
    <div class="container">
      <%= link_to root_path do %>
        <%= image_tag 'logo.jpg', :size =>'208x75' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %><!--会員ログインしていた場合-->
            <div class="current_user_header" style="display:inline-block;text-align:center">
              <li class="nav-item"><%= render 'searches/search' %></li>
              <li class="nav-item">
                <%= link_to public_item_images_path do %>
                  <%= image_tag 'item_logo.png', :size => '99x66' %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to public_post_images_path do %>
                  <%= image_tag 'new_logo.png', :size => '99x66' %>
                <% end %>
              </li>
              <li class="nav-item"><%= attachment_image_tag(current_user, :profile_image, height: "40", fallback: "no_image.jpg") %></li>
              <li class="nav-item">
                <%= link_to public_user_path(current_user.id),class: "mt-5" do %>
                <div>
                  <div style="text-align:bottom"><%= current_user.nickname %>さん</div>
                </div>
                <% end %>
              </li>
              <!--deviseで追加している場合は「current_user」でよい-->
              <li class="nav-item"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %></li>
              <li class="nav-item"><%= link_to "前の画面に戻る", 'javascript:history.back()', class: "fas fa-undo" %></li>
            </div>
          <% elsif admin_signed_in? %> <!--管理者ログインしていた場合-->
            <div class="current_user_header" style="display:inline-block;text-align:center">
            <li class="nav-item"><%= render 'searches/search' %></li>
              <li class="nav-item"><%= link_to "承認待機一覧", admin_applies_path, class: "btn btn-outline-secondary" %></li>
              <li class="nav-item"><%= link_to "ユーザ一覧", admin_users_index_path, class: "btn btn-outline-secondary "%></li>
              <li class="nav-item"><%= link_to "素材線画一覧", admin_item_images_path, class: "btn btn-outline-secondary" %></li>
              <li class="nav-item"><%= link_to "logout", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %></li>
              <li class="nav-item"><%= link_to "前の画面に戻る", 'javascript:history.back()', class: "fas fa-undo" %></li>
            </div>
          <% else %>
            <div class="current_user_header" style="display:inline-block;text-align:center">
              <li class="nav-item"><%= render 'searches/search' %></li>
              <p style="display:inline-block">こんにちは ゲストさん</p>
              <li class="nav-item"><%= link_to "ログイン",new_user_session_path, class: "btn btn-primary" %></li>
              <li class="nav-item"><%= link_to "新規登録",new_user_registration_path, class: "btn btn-success" %></li>
              <li class="nav-item"><%= link_to "前の画面に戻る", 'javascript:history.back()', class: "fas fa-undo" %></li>
            </div>
          <% end %>
        </ul>
      </div>  
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charaset="UTF-8" />
    <script src="https://kit.fontawesome.com/126ca43df6.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <title>IroDory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p><%= notice %></p>
      <%= yield %>
    </main>
    <br />
    <%= render 'layouts/footer' %>
  </body>
</html>